import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-picture-details-page',
  templateUrl: './picture-details-page.component.html',
  styleUrls: ['./picture-details-page.component.scss']
})
export class PictureDetailsPageComponent implements OnInit {
  @ViewChild('modalCont') modalCont: ElementRef;
  selPicPar;
  showModal = false;
  selPicInd = -1;
  selPicDetails = {
    pid: 1,
    image: 'assets/images/picDetails.png',
    name: 'Clean minimal BMW sport car',
    created_at: '07-09-2021',
    pngLink: 'assets/images/picDetails.png',
    jpgLink: 'assets/images/picDetails.png',
    sellerInfo: {
      name: 'Alexandra Necula',
      hire_availability: 'Available',
      photo: 'assets/images/userBig.png',
      resources: 80000,
    },
    relatedResource: [
      {
        url: 'assets/images/20.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 2,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/21.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 3,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/22.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 4,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/23.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 5,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/24.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 6,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/25.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 7,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/13.jpg',
        width: 664,
        height: 276,
        user: 'Alexandra Necula',
        pid: 8,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Premium',
      },
      {
        url: 'assets/images/14.jpg',
        width: 664,
        height: 239,
        user: 'Alexandra Necula',
        pid: 9,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/15.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 10,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/16.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 11,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/17.jpg',
        width: 338,
        height: 338,
        user: 'Alexandra Necula',
        pid: 12,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/18.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 13,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Premium',
      },
      {
        url: 'assets/images/19.jpg',
        width: 664,
        height: 286,
        user: 'Alexandra Necula',
        pid: 14,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/20.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 15,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/21.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 16,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/22.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 17,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/23.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 18,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/24.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 19,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/25.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 20,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/13.jpg',
        width: 664,
        height: 276,
        user: 'Alexandra Necula',
        pid: 21,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Premium',
      },
      {
        url: 'assets/images/14.jpg',
        width: 664,
        height: 239,
        user: 'Alexandra Necula',
        pid: 22,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/15.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 23,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/16.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 24,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/17.jpg',
        width: 338,
        height: 338,
        user: 'Alexandra Necula',
        pid: 25,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/18.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 26,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Premium',
      },
      {
        url: 'assets/images/19.jpg',
        width: 664,
        height: 286,
        user: 'Alexandra Necula',
        pid: 27,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
    ]
  };

  pagePicDetails;
  constructor(
    private router: Router,
    private route: ActivatedRoute,
  ) { }

  ngOnInit(): void {
    this.getPagePicDetails();
  }

  private getPagePicDetails() {
    const pid = this.route.snapshot.paramMap.get('pid');
    this.pagePicDetails  = {
      pid: pid,
      image: 'assets/images/picDetails.png',
      name: 'Clean minimal BMW sport car',
      created_at: '07-09-2021',
      pngLink: 'assets/images/picDetails.png',
      jpgLink: 'assets/images/picDetails.png',
      sellerInfo: {
        name: 'Alexandra Necula',
        hire_availability: 'Available',
        photo: 'assets/images/userBig.png',
        resources: 80000,
      },
      relatedResource: [
        {
          url: 'assets/images/20.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 2,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/21.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 3,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/22.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 4,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/23.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 5,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/24.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 6,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/25.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 7,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/13.jpg',
          width: 664,
          height: 276,
          user: 'Alexandra Necula',
          pid: 8,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Premium',
        },
        {
          url: 'assets/images/14.jpg',
          width: 664,
          height: 239,
          user: 'Alexandra Necula',
          pid: 9,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/15.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 10,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/16.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 11,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/17.jpg',
          width: 338,
          height: 338,
          user: 'Alexandra Necula',
          pid: 12,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/18.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 13,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Premium',
        },
        {
          url: 'assets/images/19.jpg',
          width: 664,
          height: 286,
          user: 'Alexandra Necula',
          pid: 14,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/20.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 15,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/21.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 16,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/22.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 17,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/23.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 18,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/24.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 19,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/25.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 20,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/13.jpg',
          width: 664,
          height: 276,
          user: 'Alexandra Necula',
          pid: 21,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Premium',
        },
        {
          url: 'assets/images/14.jpg',
          width: 664,
          height: 239,
          user: 'Alexandra Necula',
          pid: 22,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/15.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 23,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/16.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 24,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/17.jpg',
          width: 338,
          height: 338,
          user: 'Alexandra Necula',
          pid: 25,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
        {
          url: 'assets/images/18.jpg',
          width: 664,
          height: 442,
          user: 'Alexandra Necula',
          pid: 26,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Premium',
        },
        {
          url: 'assets/images/19.jpg',
          width: 664,
          height: 286,
          user: 'Alexandra Necula',
          pid: 27,
          downloads: 150,
          favorites: 200,
          isFavorite: 0,
          photo: 'assets/images/user.png',
          status: 'Free',
        },
      ]
    };
    
  }

  getPicDetails(e, pic, i, picArr) {
    e.stopPropagation();
    e.stopImmediatePropagation();
    e.preventDefault();
    this.selPicPar = picArr;
    this.showModal = true;
    this.selPicInd = i;
    this.selPicDetails = { ...this.selPicDetails, pid: pic.pid, image: pic.url };
    this.modalCont.nativeElement.scrollTop = 0;
  }

  showNext(e, n) {
    if ((n == -1 && this.selPicInd == 0) || (n == 1 && this.selPicInd == this.selPicPar.length - 1)) return;
    this.getPicDetails(e, this.selPicPar[this.selPicInd + n], this.selPicInd + n, this.selPicPar);
  }

  outputDetails([e, pic, i, picArr]) {
    this.getPicDetails(e, pic, i, picArr);
  }

}
