import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { AuthService } from 'src/app/data/services/auth.service';

@Component({
  selector: 'app-auth-home',
  templateUrl: './auth-home.component.html',
  styleUrls: ['./auth-home.component.scss']
})
export class AuthHomeComponent implements OnInit {
  showModal = false;
  @ViewChild('modalCont') modalCont: ElementRef;
  auth;

  images = [
    {
      url: 'assets/images/1.png',
      width: 326,
      height: 330,
      user: 'Alexandra Necula',
      pid: 30,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/2.png',
      width: 490,
      height: 330,
      user: 'Alexandra Necula',
      pid: 31,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/3.png',
      width: 490,
      height: 330,
      user: 'Alexandra Necula',
      pid: 32,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Premium',
    },
    {
      url: 'assets/images/4.png',
      width: 502,
      height: 330,
      user: 'Alexandra Necula',
      pid: 33,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/post-job.png',
      width: 752,
      height: 742,
      user: 'Alexandra Necula',
      pid: 34,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Premium',
    },
    {
      url: 'assets/images/5.png',
      width: 415,
      height: 265,
      user: 'Alexandra Necula',
      pid: 35,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/6.png',
      width: 508,
      height: 265,
      user: 'Alexandra Necula',
      pid: 36,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/7.png',
      width: 400,
      height: 265,
      user: 'Alexandra Necula',
      pid: 37,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/8.png',
      width: 482,
      height: 265,
      user: 'Alexandra Necula',
      pid: 38,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Premium',
    },
    {
      url: 'assets/images/9.png',
      width: 498,
      height: 328,
      user: 'Alexandra Necula',
      pid: 39,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/10.png',
      width: 490,
      height: 328,
      user: 'Alexandra Necula',
      pid: 40,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },

    {
      url: 'assets/images/11.png',
      width: 488,
      height: 328,
      user: 'Alexandra Necula',
      pid: 41,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },

    {
      url: 'assets/images/12.png',
      width: 331,
      height: 328,
      user: 'Alexandra Necula',
      pid: 42,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/1.png',
      width: 326,
      height: 330,
      user: 'Alexandra Necula',
      pid: 43,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/2.png',
      width: 490,
      height: 330,
      user: 'Alexandra Necula',
      pid: 44,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/river-surrounded-by-forests-cloudy-sky-thuringia-germany.png',
      width: 1920,
      height: 640,
      user: 'Alexandra Necula',
      pid: 45,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/3.png',
      width: 490,
      height: 330,
      user: 'Alexandra Necula',
      pid: 46,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/4.png',
      width: 502,
      height: 330,
      user: 'Alexandra Necula',
      pid: 47,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/5.png',
      width: 415,
      height: 265,
      user: 'Alexandra Necula',
      pid: 48,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/6.png',
      width: 508,
      height: 265,
      user: 'Alexandra Necula',
      pid: 49,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/7.png',
      width: 400,
      height: 265,
      user: 'Alexandra Necula',
      pid: 50,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/8.png',
      width: 482,
      height: 265,
      user: 'Alexandra Necula',
      pid: 51,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Premium',
    },
    {
      url: 'assets/images/9.png',
      width: 498,
      height: 328,
      user: 'Alexandra Necula',
      pid: 52,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
    {
      url: 'assets/images/10.png',
      width: 490,
      height: 328,
      user: 'Alexandra Necula',
      pid: 53,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },

    {
      url: 'assets/images/11.png',
      width: 488,
      height: 328,
      user: 'Alexandra Necula',
      pid: 54,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },

    {
      url: 'assets/images/12.png',
      width: 331,
      height: 328,
      user: 'Alexandra Necula',
      pid: 55,
      downloads: 150,
      favorites: 200,
      isFavorite: 0,
      photo: 'assets/images/user.png',
      status: 'Free',
    },
  ];

  slides = [
    {
      images: [
        'assets/images/slideGrids/1.jpg',
        'assets/images/slideGrids/2.jpg',
        'assets/images/slideGrids/3.jpg',
      ],
      title: 'Freepik by Juan Sin Miedo',
      resources: 15
    },
    {
      images: [
        'assets/images/slideGrids/4.jpg',
        'assets/images/slideGrids/5.jpg',
        'assets/images/slideGrids/6.jpg',
      ],
      title: 'Potraits',
      resources: 100
    },
    {
      images: [
        'assets/images/slideGrids/7.jpg',
        'assets/images/slideGrids/8.jpg',
        'assets/images/slideGrids/9.jpg',
      ],
      title: 'Instagram Templates',
      resources: 140
    },
    // {
    //   images: [
    //     'assets/images/slideGrids/10.jpg',
    //     'assets/images/slideGrids/11.jpg',
    //     'assets/images/slideGrids/12.jpg',
    //   ],
    //   title: 'Your Design Here',
    //   resources: 140
    // },
  ];

  selPicPar;

  selPicInd = -1;


  banners = [
    { img: 'assets/images/auth-banner.png', title: 'Photos that tells design stories', subtitle: 'Find Free Illustrations, Stock Photos and Designs' },
    { img: 'assets/images/banner2.png', title: 'Graphic resources for everyone', subtitle: 'Find Free Illustrations, Stock Photos and Designs' },
  ];

  activeTab = 'afreepik';

  selPicDetails = {
    pid: 1,
    image: 'assets/images/picDetails.png',
    name: 'Clean minimal BMW sport car',
    created_at: '07-09-2021',
    pngLink: 'assets/images/picDetails.png',
    jpgLink: 'assets/images/picDetails.png',
    sellerInfo: {
      name: 'Alexandra Necula',
      hire_availability: 'Available',
      photo: 'assets/images/userBig.png',
      resources: 80000,
    },
    relatedResource: [
      {
        url: 'assets/images/20.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 2,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/21.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 3,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/22.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 4,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/23.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 5,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/24.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 6,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/25.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 7,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/13.jpg',
        width: 664,
        height: 276,
        user: 'Alexandra Necula',
        pid: 8,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Premium',
      },
      {
        url: 'assets/images/14.jpg',
        width: 664,
        height: 239,
        user: 'Alexandra Necula',
        pid: 9,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/15.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 10,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/16.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 11,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/17.jpg',
        width: 338,
        height: 338,
        user: 'Alexandra Necula',
        pid: 12,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/18.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 13,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Premium',
      },
      {
        url: 'assets/images/19.jpg',
        width: 664,
        height: 286,
        user: 'Alexandra Necula',
        pid: 14,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/20.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 15,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/21.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 16,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/22.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 17,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/23.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 18,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/24.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 19,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/25.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 20,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/13.jpg',
        width: 664,
        height: 276,
        user: 'Alexandra Necula',
        pid: 21,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Premium',
      },
      {
        url: 'assets/images/14.jpg',
        width: 664,
        height: 239,
        user: 'Alexandra Necula',
        pid: 22,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/15.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 23,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/16.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 24,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/17.jpg',
        width: 338,
        height: 338,
        user: 'Alexandra Necula',
        pid: 25,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
      {
        url: 'assets/images/18.jpg',
        width: 664,
        height: 442,
        user: 'Alexandra Necula',
        pid: 26,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Premium',
      },
      {
        url: 'assets/images/19.jpg',
        width: 664,
        height: 286,
        user: 'Alexandra Necula',
        pid: 27,
        downloads: 150,
        favorites: 200,
        isFavorite: 0,
        photo: 'assets/images/user.png',
        status: 'Free',
      },
    ]
  };

  constructor(
    private authService: AuthService
  ) { }

  ngOnInit(): void {
    this.getAuth();
  }

  private getAuth() {
    this.authService.user.subscribe(auth => {
      this.auth = auth;
    })
  }

  switchTab(owner) {
    this.activeTab = owner;
  }

  getPicDetails(e, pic, i, parArr) {
    e.stopPropagation();
    e.stopImmediatePropagation();
    e.preventDefault();
    this.selPicPar = parArr;
    this.showModal = true;
    this.selPicInd = i;
    this.selPicDetails = { ...this.selPicDetails, pid: pic.pid, image: pic.url };
    this.modalCont.nativeElement.scrollTop = 0;
  }

  showNext(e, n) {
    if ((n == -1 && this.selPicInd == 0) || (n == 1 && this.selPicInd == this.selPicPar.length - 1)) return;
    this.getPicDetails(e, this.selPicPar[this.selPicInd + n], this.selPicInd + n, this.selPicPar);
  }

  outputDetails([e, pic, i, picArr]) {
    this.getPicDetails(e, pic, i, picArr);
  }

}
